### ISSUE TITLE
Please may you add the documentation to access the API

### ISSUE THREAD

**Issue by haydenfordz** [EricAndrechek/VCController#1]
I have had a quick look through the code and cannot see to find where to access the API, please can you leave instructions in the README file or in the code
Cheers
Hayden

**Comment by JadeMin** [comment]
absurdity

**Comment by hologram2016** [comment]
huh?

**Comment by KlartNET** [comment]
references

http://localhost:6969/ :
https://github.com/EricAndrechek/VCController/blob/5c9fa4cc8a2d8fee5f9d24bad4e7daf1adb6a192/VCController.plugin.js#L109

http://localhost:6969/mute :
https://github.com/EricAndrechek/VCController/blob/5c9fa4cc8a2d8fee5f9d24bad4e7daf1adb6a192/VCController.plugin.js#L82

http://localhost:6969/disconnect :
https://github.com/EricAndrechek/VCController/blob/5c9fa4cc8a2d8fee5f9d24bad4e7daf1adb6a192/VCController.plugin.js#L98

etc...

**Comment by EricAndrechek** [comment]
Hi @JadeMin and @haydenfordz, this project is now dead. If you would like a new and functional version with many of these bugs fixed, check out [DCController](https://github.com/Piripe/BDPlugins).
