### ISSUE TITLE
The proper way of doing things

### ISSUE THREAD

**Issue by QbDesu** [EricAndrechek/VCController#2]
```js
const vc = BdApi.findModuleByProps('toggleSelfDeaf');
// self mute
vc.toggleSelfMute(); //toggle
vc.enable(); //unmute
// self deafen
vc.toggleSelfDeaf();
// camera
vc.setVideoEnabled(true); // on
vc.setVideoEnabled(false); // off
// settings
const UserSettingsWindow = ZLibrary.DiscordModules.UserSettingsWindow;
UserSettingsWindow.open(ZLibrary.DiscordModules.DiscordConstants.UserSettingsSections.ACCOUNT); // default tab when clicking the button
UserSettingsWindow.open(ZLibrary.DiscordModules.DiscordConstants.UserSettingsSections.VOICE);
UserSettingsWindow.open(ZLibrary.DiscordModules.DiscordConstants.UserSettingsSections.EXPERIMENTS);
```
couldn't find simple methods to open the screenshare menu (not that would be useful imo) or stop the screenshare. But that's some work left for you.

**Comment by legop3** [comment]
i believe a rewrite of this plugin is a very good idea...

**Comment by DingleFlop** [comment]
Thank you for this comment. I rewrote it to find buttons via aria-label and then JS simulate a click on them using click().

Using the BD API is much, much, much better though.

**Comment by EricAndrechek** [comment]
Hi @QbDesu @legop3 and @DingleFlop, this project is now dead. If you would like a new and functional version with many of these bugs fixed, check out [DCController](https://github.com/Piripe/BDPlugins).
