### ISSUE TITLE
Endpoints perform incorrect functions with GameActivityToggle

### ISSUE THREAD

**Issue by QbDesu** [EricAndrechek/VCController#3]
Using GameActivityToggle (or any other plugin that adds a button), breaks the heuristic for selecting the correct function (button to click) for the endpoints.

**Comment by EricAndrechek** [comment]
Hi @QbDesu, this project is now dead. If you would like a new and functional version with many of these bugs fixed, check out [DCController](https://github.com/Piripe/BDPlugins).
