### ISSUE TITLE
Listen on localhost/127.0.0.1 instead of 0.0.0.0

### ISSUE THREAD

**Issue by QbDesu** [EricAndrechek/VCController#5]
The way the plugin is set up it listens for incoming requests from all interfaces. Meaning it takes in requests from every device on the network. The default should be `127.0.0.1`/`localhost` and maybe have it be configurable.
The host can be specified as the second parameter of `server.listen` https://nodejs.org/api/net.html#net_server_listen

**Comment by EricAndrechek** [comment]
Hi @QbDesu, this project is now dead. If you would like a new and functional version with many of these bugs fixed, check out [DCController](https://github.com/Piripe/BDPlugins).
